parameters:
    d2d.locales: en|pl
    d2d.doc_limit: 22
    d2d.doc_dir_public: '%kernel.project_dir%/public/build/documentations'
    d2d.doc_dir_private: '%kernel.project_dir%/private/build/documentations'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Exception,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']